[package]
name = "another_physics_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
dialoguer = "0.10"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]
